// SuperHero Main Include File
// Version 1.3.0

#if defined _shero_included
  #endinput
#endif
#define _shero_included

//Backwards compatibility
#include <amxmodx>
#include <amxmisc>
#include <fakemeta>
#include <hamsandwich>
#include <fun>
#include <csx>
#include <cstrike>

#include <sh_core_main>
#include <sh_core_objectives>
#include <sh_core_hpap>
#include <sh_core_speed>
#include <sh_core_gravity>
#include <sh_core_weapons>
#include <sh_core_shieldrestrict>
